- name: CIS Hardening for RHEL 9.1 SEC-2.9 (services)
  hosts: localhost
  become: true
  ignore_errors: yes
  tasks:

    - name: Disable unused services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - telnet
        - rsh
        - rlogin
        - rexec
        - rstatd
        - rsyslog
        - dhcpd
        - nfs
        - snmpd
        - cups
        - avahi-daemon
        - ndflock
        - rpcgssd
        - rpcbind
        - rpcidmapd
        - ftpd
        - httpd
        - 


    - name: Remove unwanted rpm packages SEC-2.9.4 
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - xorg-x11-server-common
        - openldap-servers
        - 
  
    - name: Enable and start required services SEC-2.9.2
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - sshd
        - firewalld
        - chronyd

    - name: Set permissions and ownership on critical files
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
      loop:
        - { path: '/etc/passwd', state: 'file', mode: '0644', owner: 'root', group: 'root' }
        - { path: '/etc/shadow', state: 'file', mode: '0600', owner: 'root', group: 'root' }
        - { path: '/etc/group', state: 'file', mode: '0644', owner: 'root', group: 'root' }
        - { path: '/etc/gshadow', state: 'file', mode: '0600', owner: 'root', group: 'root' }
        - { path: '/etc/ssh/sshd_config', state: 'file', mode: '0600', owner: 'root', group: 'root' }
      notify: Restart sshd service

          #    - name: Configure firewall rules
          # firewalld:
          # zone: public
          # permanent: true
          # state: enabled
          # immediate: true
          # service: "{{ item }}"
          # loop:
          # - ssh
          # - http
          # - https

    # Add more tasks to perform additional hardening steps based on CIS benchmarks

  handlers:
    - name: Restart sshd service
      service:
        name: sshd
        state: restarted





################################################################################################