- hosts: all
  become: true
  ignore_errors: yes
  #vars_files:
    #- ./vars/const.yml
  roles:
    - { role: os_hardening_copy, when: BUILD_METHOD == 'hardening' }
    - { role: ssh_hardening , when: BUILD_METHOD == 'ssh_hardening' }
