#CIMB required tasks ### ##24apr2024
- name: create folder
  shell: mkdir /etc/systemd/system/rescue.service.d
  
- name: 1.4.2 Ensure authentication is required when booting into rescue mode bkp
  copy:    
    src: /etc/systemd/system/rescue.service.d/{{ item }}
    dest: /etc/systemd/system/rescue.service.d/{{ item }}_{{ ansible_date_time.iso8601 }}.bkp    
    remote_src: yes     
    owner: root    
    group: root     
    mode: '0755'    
    force: yes    
  with_items:
    - 00-require-auth.conf
    
- name: 1.4.2 Ensure authentication is required when booting into rescue mode
  template:
    src: 'templates/shell/{{ item.src }}'
    dest: '/etc/systemd/system/rescue.service.d/{{ item.dest }}'
    owner: root
    group: root
    #mode: 755
    #backup: yes
  with_items:
    - { src: '00-require-auth.j2', dest: '00-require-auth.conf' }

- name: 5.2.7 Restrict root and system accounts from direct logins
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^MaxSessions', line: 'MaxSessions 4' }
  notify: Restart sshd


- name: 5.6.1.9 Ensure default user umask is set - /etc/profile
  lineinfile:
    path: /etc/profile
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^umask', line: 'umask 027' }
    - { regexp: '^readonly', line: 'readonly TMOUT=900 ; export TMOUT' }
    
- name: 5.6.1.9 Ensure default user umask is set - /etc/bashrc
  lineinfile:
    path: /etc/bashrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^umask', line: 'umask 027' }
    - { regexp: '^readonly', line: 'readonly TMOUT=900 ; export TMOUT' }

- name: 5.6.1.9 Set default umask for all sh files
  shell: for file in /etc/profile.d/*.sh ;do echo "umask 027" >> "$file"; done

- name: 4.1.1.4 Ensure audit_backlog_limit is sufficient
  shell: grubby --update-kernel ALL --args 'audit_backlog_limit=64'

- name: 4.1.3.5 Ensure events that modify the system's network environment are collected - /etc/sysconfig/network-scripts
  template:
    src: 'templates/shell/{{ item.src }}'
    dest: '/etc/audit/rules.d/{{ item.dest }}'
    owner: root
    group: root
    #mode: 755
    #backup: yes
  with_items:
    - { src: '50-system_local.j2', dest: '50-system_local.rules' }
    
- name: 4.1.3.7 Ensure unsuccessful file access attempts are collected - b32 EACCES
  template:
    src: 'templates/shell/{{ item.src }}'
    dest: '/var/tmp/{{ item.dest }}'
    owner: root
    group: root
    mode: 755
    #backup: yes
  with_items:
    - { src: '50-access_rules.j2', dest: '50-access_rules.sh' }

- name: 4.1.3.7 run script
  command: sh /var/tmp/50-access_rules.sh

- name: 4.1.3.5 Ensure events that modify the system's network environment are collected - reload
  shell: augenrules --load