#CIMB required tasks (5.6.1.9) ### ##24apr2024


- name: 5.6.1.9 - Set default umask for users
  lineinfile:
    path: /etc/profile
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^umask', line: 'umask 027' }
    
- name: Set default umask for users SEC-5.4.2
  lineinfile:
    path: /etc/bashrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^umask', line: 'umask 027' }

- name: Set default umask for all sh files SEC-5.4.2
  shell: for file in /etc/profile.d/*.sh ;do echo "umask 027" >> "$file"; done
   
- name: Remove world-writable permissions on user home directories - sec-6.1.9
  file:
    path: "{{ item }}"
    mode: '0700'
  with_fileglob:
    - /home/*
    

    