#CIMB required tasks ### 5.4.1 Ensure custom authselect profile is used


#####pam passsword quality#############
- name: password history configs and commands to enable pwhistory
  shell: "{{ item }}"
  with_items:
    -  authselect enable-feature with-pwhistory
    
- name: 5.5.1 - Ensure password creation requirements are configured
  lineinfile:
    dest: "/etc/security/pwquality.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  with_items:
    - { regexp: "^#?minlen = ", line: "minlen = {{ cis_pwquality_minlen }}" }
    - { regexp: "^#?dcredit = ", line: "dcredit = {{ cis_pwquality_dcredit }}" }
    - { regexp: "^#?ucredit = ", line: "ucredit = {{ cis_pwquality_ucredit }}" }
    - { regexp: "^#?ocredit = ", line: "ocredit = {{ cis_pwquality_ocredit }}" }
    - { regexp: "^#?lcredit = ", line: "lcredit = {{ cis_pwquality_lcredit }}" }
    - { regexp: "^#?remember = ", line: "remember = {{ cis_pwquality_remember }}" }
