# article followed https://access.redhat.com/solutions/6980935
---
#- name: upgrade authselect and PAM
 # shell: dnf upgrade authselect pam

- name: Check if PAM package are installed
  command: rpm -qa | grep -i "{{ item }}"
  loop:
    - authselect
    - pam
  register: package_check
  
- name: Print package installation results
  debug:
    msg: "authselect and pam package is installed and upgraded"
  when: package_check is succeeded

- name: Check if PAM package are installed
  command: authselect enable-feature with-pwhistory


####################################################################
# 5.3.2 Ensure lockout for failed password attempts is configured
- name: 5.3.2 and 5.3.3 - Ensure authselect is installed for linking and later command running
  yum:
    name: authselect
    state: present

- name: faillock configs and commands to enable faillock
  shell: "{{ item }}"
  with_items:
    -  authselect current
    -  authselect check
    -  authselect enable-feature with-faillock
    -  authselect select sssd with-faillock
    -  grep -qxF 'deny=4' /etc/security/faillock.conf || echo 'deny=4' >> /etc/security/faillock.conf
    -  grep -qxF 'unlock_time=900' /etc/security/faillock.conf || echo 'unlock_time=900' >> /etc/security/faillock.conf
    -  grep -qxF 'silent' /etc/security/faillock.conf || echo 'silent' >> /etc/security/faillock.conf
    -  grep -qxF 'dir=/var/log/faillock' /etc/security/faillock.conf || echo 'dir=/var/log/faillock' >> /etc/security/faillock.conf

- name: 5.3.2 and 5.3.3 - Ensure lockout for failed login attempts and password history - for password-auth and system-auth
  template:
    src: 'templates/{{ item.src }}'
    dest: '/etc/pam.d/{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - { src: 'password-auth-local.j2', dest: 'password-auth-local' }
    - { src: 'system-auth-local.j2', dest: 'system-auth-local' }
  
###################### for RHEL8.7 or below ##########################
- block:
  - name: Only for RHEL 8.7 or below version PAM change
    shell: df -h 
  when: RHEL_VERSION == "8.7"
  
